name: 'setup-msstore-cli'
description: 'Setup Microsoft Store Developer CLI'
author: 'Microsoft'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  version:
    required: false
    description: "The version of the Microsoft Store CLI to be downloaded and configured (e.g. 'v0.3.0')."
    default: 'latest'
runs:
  using: 'node20'
  main: 'dist/index.js'
